[project]
name = "munibot"
revision = "1.0"

[profiles.default]
DATABASE_URL = { description = "Database connection string", required = true }
DISCORD_APPLICATION_ID = { description = "Discord app ID", required = true }
DISCORD_CLIENT_SECRET = { description = "Discord client secret", required = true }
DISCORD_PUBLIC_KEY = { description = "Discord public key", required = true }
DISCORD_TOKEN = { description = "Discord token", required = true }
TWITCH_CLIENT_ID = { description = "Twitch client ID", required = true }
TWITCH_CLIENT_SECRET = { description = "Twitch client secret", required = true }
TWITCH_TOKEN = { description = "Twitch token secret" }
VENTR_ALLOWLIST = { description = "Discord user IDs to allow ventriloquism for" }

[profiles.development]
# development profile inherits all secrets from default profile
# only define secrets here that need different values or settings than default
DATABASE_URL = { default = "mysql://munibot:sillylittlepassword@localhost/munibot" }

# new secrets
# REDIS_URL = { description = "Redis connection URL for caching", required = false, default = "redis://localhost:6379" }
